pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Check Python') {
            steps {
                dir('pythontest1') {
                    bat 'python --version'
                }
            }
        }

        stage('Run dupletter') {
            steps {
                dir('pythontest1') {
                    bat 'python dupletter.py'
                }
            }
        }

        stage('Run fibo') {
            steps {
                dir('pythontest1') {
                    bat 'python fibo.py'
                }
            }
        }

        stage('Run OOP concepts') {
            steps {
                dir('pythontest1') {
                    bat 'python oop_concepts.py'
                }
            }
        }

        stage('Run pallidrome') {
            steps {
                dir('pythontest1') {
                    bat 'python pallidrome.py'
                }
            }
        }

        stage('Run print duplicates') {
            steps {
                dir('pythontest1') {
                    bat 'python printdupsletters.py'
                }
            }
        }

        stage('Run reverse') {
            steps {
                dir('pythontest1') {
                    bat 'python reverse1.py'
                }
            }
        }
    }
}